// Generated by gencpp from file ros_service/serviceResponse.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_MESSAGE_SERVICERESPONSE_H
#define ROS_SERVICE_MESSAGE_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_service
{
template <class ContainerAllocator>
struct serviceResponse_
{
  typedef serviceResponse_<ContainerAllocator> Type;

  serviceResponse_()
    : out()  {
    }
  serviceResponse_(const ContainerAllocator& _alloc)
    : out(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _out_type;
  _out_type out;





  typedef boost::shared_ptr< ::ros_service::serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_service::serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct serviceResponse_

typedef ::ros_service::serviceResponse_<std::allocator<void> > serviceResponse;

typedef boost::shared_ptr< ::ros_service::serviceResponse > serviceResponsePtr;
typedef boost::shared_ptr< ::ros_service::serviceResponse const> serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_service::serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_service::serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_service::serviceResponse_<ContainerAllocator1> & lhs, const ::ros_service::serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.out == rhs.out;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_service::serviceResponse_<ContainerAllocator1> & lhs, const ::ros_service::serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_service::serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service::serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service::serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service::serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service::serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service::serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_service::serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6f143c7fbdeafd31860d9ba817bed9d";
  }

  static const char* value(const ::ros_service::serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6f143c7fbdeafd3ULL;
  static const uint64_t static_value2 = 0x1860d9ba817bed9dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_service::serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_service/serviceResponse";
  }

  static const char* value(const ::ros_service::serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_service::serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] out\n"
"\n"
;
  }

  static const char* value(const ::ros_service::serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_service::serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_service::serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_service::serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "out[]" << std::endl;
    for (size_t i = 0; i < v.out.size(); ++i)
    {
      s << indent << "  out[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.out[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICE_MESSAGE_SERVICERESPONSE_H
